### PR TITLE
Fix misc-modules/ for kernel v5.6.7

### PR DESCRIPTION
**Pull request by ftheile**

### CODE REVIEW

**Comment by gabcoh** [comment]
Here's the [lmkl link](https://lore.kernel.org/linux-fsdevel/20191225172228.GA13378@avx2/#r)

And the [commit](https://github.com/torvalds/linux/commit/d56c0d45f0e27f814e87a1676b6bdccccbc252e9)

**Comment by dwalkes** [comment]
Thanks @ftheile and @gabcoh for sharing.

Before merging I'd like to include logic that allows this fix to work with previous kernel versions as well, so people testing on earlier kernels won't have compile errors.  See https://github.com/martinezjavier/ldd3/issues/42#issuecomment-622967442 for an example.

**Comment by dwalkes** [comment]
I believe this is addressed with https://github.com/martinezjavier/ldd3/pull/46 but please re-open if not

**Comment by ftheile** [comment]
> I believe this is addressed with #46 but please re-open if not

Yes, all is fine, thank you!  
I can confirm everything builds on ArchLinux with Kernel 5.8.5-arch1-1.

**Pull request closed without merging**
