### PR TITLE
Support 5.x kernels

### PR DESCRIPTION
**Pull request by dwalkes**
A rollup of changes from [Advanced Embedded Software Development](https://sites.google.com/colorado.edu/ecen5013/home) Fall 2019 semester, focusing on adding support for 5.x kernels, Ubuntu 18.04 native builds, 2018.05 Buildroot release, and warrior branch of Yocto project.

Summary of Changes
* Added eclipse support for ease of source code browsing/searching, see comments in the README file.
* Disabled sbull, snull, and short modules which are not compiling on 5.0 at this time.
* Modified access_ok wrapper to support kernel versions above or below 5.0
* Added module_load and module_unload scripts to misc-modules.
* Fixed several 5.x kernel build issues across several kernel modules.
* Added misc-progs/test/nonblock.sh script to help with testing of non blocking IO
* Added scull-shared directory and symlinks to avoid duplicating logic for components shared across all scull implementations.
* Used mutex insetad of semaphore for semaphores used as mutexes.

### CODE REVIEW

**Comment by dwalkes** [comment]
@martinezjavier I have included a rollup of changes I've made to support the course I taught last semester.  I'm going to plan to keep this updated to support latest Ubuntu builds as well as builds on Buildroot and Yocto versions we use for the course.  Let me know if you'd like any changes to these, or if you'd prefer I start a new repo instead.  I think there are several open pull requests which are resolved by this one, I've put comments in those as well.

**Comment by dwalkes** [comment]
@martinezjavier and @mbgg are you planning to keep this repository up to date going forward and, if so, would you like to include these commits or should I create a parallel project to track the commits for my class?

**Comment by martinezjavier** [comment]
@dwalkes sorry for not answering before and thanks a lot for the patches!

I started this repo a decade ago when I was also teaching and haven't really had time to take care of it for years.

Some time ago @mbgg mentioned that he was interested in keeping the repo up-do-date but he has also been busy.

If you want I can include you as a collaborator as well or feel free to fork the project. For some reasons this repository seems to be referenced in different places so probably would make sense to do the former if you prefer that option.

**Comment by dwalkes** [comment]
@martinezjavier thanks for the response!

> If you want I can include you as a collaborator as well

That would be great, thanks.  I'll still propose all my changes as pull requests from my class repository if you want to weigh in but I'll plan on updating at least once per year as long as I'm teaching my class.

I think it makes more sense to keep this repository going rather than starting a new one as yours has been forked/starred most often and it was still the most up to date of the Linux Device Driver book source code I found when I started my class last year.

**Comment by martinezjavier** [comment]
> I think it makes more sense to keep this repository going rather than starting a new one

@dwalkes Ok, great. I've invited you as a collaborator now, thanks!

**Comment by jypan-ccu** [comment]
Thank you all guys for kernel 5.x update. I am a newbie of github and try to fix all of snull/sbull/short with timespec64 and jiq/jit/seq with timers. Wish you can try them and I am also going to teach my class next semester with these codes. I have not fully tried all, but I modified them based on a previous version from @martinezjavier. 
https://github.com/jypan-ccu/ldd3-k5.git

**Comment by dwalkes** [comment]
@jypan-ccu thanks for your comments and for helping with updates.

I have some cleanup I hope to do this weekend in preparation for the semester as well.  

As for your changes if you could [fork this repo](https://docs.github.com/en/enterprise/2.13/user/articles/fork-a-repo#:~:text=A%20fork%20is%20a%20copy,point%20for%20your%20own%20idea.) and then [create a pull request from your fork](https://docs.github.com/en/enterprise/2.15/user/articles/creating-a-pull-request-from-a-fork) this will be the easiest change for us to incorporate them.

**Pull request merged**
