### PR TITLE
Support linux kernel 5.9

### PR DESCRIPTION
**Pull request by jypan-ccu**
update sbull and short

### CODE REVIEW

**Comment by jypan-ccu** [comment]
support 5.9 and turn debug off

**Comment by dwalkes** [comment]
@jypan-ccu thanks for this, sorry I didn't notice it earlier.  Can you please [rebase this branch](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) on top of the master branch?

**Comment by jypan-ccu** [comment]
@dwalkes  I try to rebase it already, but I don't  know if it is rebased successfully or not? 
That says "This branch has no conflicts with the base branch when rebasing".

**Review by dwalkes — APPROVED** [review]

**Comment by dwalkes** [comment]
@jypan-ccu rebased now, thanks.  I've merged into master.

**Pull request merged**
